### ISSUE TITLE
Find a issue number by string

### ISSUE THREAD

**Issue by guilhermeprokisch** [peter-evans/find-comment#16]
It's possible to a similar logic to find the Issue number by string?

**Comment by peter-evans** [comment]
Hi @guilhermeprokisch 

I don't follow what you want to do. Please show me your workflow or let me know the following so I can try and help you:

- What the event type that your workflow is triggered by?
- What information do you want to know during the workflow? (The issue number of some issue?)

**Comment by guilhermeprokisch** [comment]
Hi @peter-evans 

In my workflow, I have just the issue title but I don't know the issue number. So I was wondering if is possible to tweak this project to do this job. 

Does that make sense?

Thanks!

**Comment by peter-evans** [comment]
I still need to know more detail to help you. What event type is the workflow? Why do you have the title? Where does that input come from? Please explain in detail what you are trying to do.

The reason I need more info is because the answer to where to get the `issue_number` varies wildly depending on the context in which the workflow is running. For example, the `issue_comment` event has a context property where you have access to the number at `github.event.issue.number`. So depending on the workflow it won't be necessary to call an action to lookup the number, it's right there in the `github` context.

**Comment by peter-evans** [comment]
Closing this for now.
