### ISSUE TITLE
Dependabot finding

### ISSUE THREAD

**Issue by Lasse4** [peter-evans/find-comment#223]
We have already the newest version of your action.
Dependabot finds the following dependencies in our repo:

![image](https://github.com/peter-evans/find-comment/assets/103564285/6e06cd94-1b91-4409-ad58-83698bb3303e)
Will these be fixed?

**Comment by peter-evans** [comment]
Hi @Lasse4 

Not sure why you are seeing those. Please check again if you have the most up to date version of the code because it looks like you have copied the code somewhere else. I can assure you that this repo does not have those vulnerability alerts. I have dependabot enabled to raise PRs for any alerts like this.
