### ISSUE TITLE
cannot find matching comments when the thread in the PR exceeds 30 comments

### ISSUE THREAD

**Issue by p-costa** [peter-evans/find-comment#24]
Hi,

I am testing this workflow and it works like a charm, except for this issue that I'm facing:

If the comment that matches the keyword that I seek is the 31st comment or more in the thread, `find-comment` does not detect it. Have you experienced this issue?

Thank you,
Pedro

**Comment by p-costa** [comment]
Perhaps the discussion [here](https://github.com/chillu/github-dashing/issues/29) is relevant, and this [solution](https://github.com/chillu/github-dashing/issues/29#issuecomment-379461075) may fix the issue.

**Comment by peter-evans** [comment]
Hi @p-costa 

Yes, this is because of the default per_page on API requests. The `Octokit` instance uses the `octokit-paginate-rest` plugin and I though it was in use already, but I might not be using it at all. I'll investigate.

https://github.com/actions/toolkit/blob/main/packages/github/src/utils.ts#L22

**Comment by p-costa** [comment]
Thank you, @peter-evans ! Looking forward to hearing from you.

**Comment by peter-evans** [comment]
This should be fixed in the latest release. Thanks for reporting!

**Comment by p-costa** [comment]
Perfect! I tested and it worked fine!
