### ISSUE TITLE
Find/Get the Pull Request description

### ISSUE THREAD

**Issue by roi-zentner** [peter-evans/find-comment#74]
Hi @peter-evans, I really like this action because how seamlessly it finds comments on other repositories.

Can this be enhanced to get the PR description/body?

If so, I would use your other action (Create or Update Comment) to update the PR description (would require you to update that one as well).

Please :)

**Comment by peter-evans** [comment]
Hi @roi-zentner 

I would like to keep this action (and [create-or-update-comment](https://github.com/peter-evans/create-or-update-comment)) focused on comments. I think actions work best when they do one thing and do it well. Adding this functionality would be more than an "enhancement," it would be adding two completely separate code paths because the entities/APIs are completely different.

If you can't find any actions on the marketplace to help you with want you want to do then the next best thing is [github-script](https://github.com/actions/github-script). That action can help you call the APIs you need on GitHub.

**Comment by audy** [comment]
For anyone else who arrives here looking for the same thing: you can get the PR description/body by using `${{ github.event.pull_request.body }}` in the GitHub action.
